module.exports = {
  stories: ['../src/**/*.stories.js'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-a11y',
    '@storybook/addon-backgrounds',
    '@storybook/addon-cssresources',
    '@storybook/addon-design-assets',
    '@storybook/addon-docs',
    '@storybook/addon-events',
    '@storybook/addon-graphql',
    '@storybook/addon-jest',
    '@storybook/addon-knobs/register',
    '@storybook/addon-queryparams',
    '@storybook/addon-storysource',
    '@storybook/addon-viewport',
    '@storybook/theming',
    '@storybook/preset-create-react-app',
    '@storybook/addon-actions',
  ],
};
